import { useEffect, useMemo, useState } from 'react';
import type { ReactNode } from 'react';
import { BarChart3, Bike, Boxes, Check, ChevronRight, CircleDollarSign, CloudOff, FileText, Languages, LayoutDashboard, Menu, Moon, PackagePlus, Plus, Printer, RefreshCw, Search, Settings, ShoppingCart, Sun, Tag, Trash2, TrendingUp, Users, Wifi, X } from 'lucide-react';
import './styles.css';

type Product={id:string;name:string;my:string;sku:string;category:string;price:number;stock:number;min:number;color:string;serial?:string};
type CartItem=Product&{qty:number};
type Sale={id:string;receipt:string;total:number;items:number;status:'SYNCED'|'PENDING_UPLOAD'|'CONFLICT';time:string};
const products:Product[]=[
 {id:'p1',name:'Trailblazer 27.5 Mountain Bike',my:'တောင်တက်စက်ဘီး Trailblazer',sku:'BIK-MTB-275',category:'Bicycles',price:1290000,stock:4,min:2,color:'#dff3ee',serial:'TB275-2401'},
 {id:'p2',name:'City Glide Hybrid Bike',my:'မြို့တွင်းစီး စက်ဘီး',sku:'BIK-HYB-001',category:'Bicycles',price:890000,stock:7,min:2,color:'#e8edff'},
 {id:'p3',name:'Urban Commuter Helmet',my:'လုံခြုံရေးဦးထုပ်',sku:'HEL-URB-002',category:'Helmets',price:65000,stock:18,min:8,color:'#fff0da'},
 {id:'p4',name:'USB Rechargeable Light Set',my:'USB မီးအလင်းအစု',sku:'LGT-USB-003',category:'Lights',price:38000,stock:24,min:10,color:'#f1e8ff'},
 {id:'p5',name:'Heavy Duty U-Lock',my:'သံမဏိသော့',sku:'LCK-U-004',category:'Locks',price:42000,stock:3,min:5,color:'#ffe4e4'},
 {id:'p6',name:'700x28C Road Tire',my:'700x28C လမ်းစက်ဘီးတာယာ',sku:'TIR-700-005',category:'Tires',price:58000,stock:12,min:5,color:'#e8f4ff'},
 {id:'p7',name:'Floor Pump Pro',my:'လေထိုးစက်',sku:'PMP-FLR-006',category:'Tools',price:76000,stock:9,min:3,color:'#e9f6e5'},
 {id:'p8',name:'Kids Safety Bell',my:'ကလေးစက်ဘီး ခေါင်းလောင်း',sku:'ACC-BEL-007',category:'Accessories',price:18000,stock:2,min:5,color:'#fff0f5'}
];
const money=(n:number)=>new Intl.NumberFormat('en-US').format(n)+' MMK';
const initialSales:Sale[]=[{id:'s1',receipt:'CF-260915-001',total:1430000,items:2,status:'SYNCED',time:'10:42 AM'},{id:'s2',receipt:'CF-260915-002',total:65000,items:1,status:'SYNCED',time:'09:18 AM'},{id:'s3',receipt:'CF-260914-018',total:114000,items:3,status:'SYNCED',time:'Yesterday'}];
const t=(key:string,lang:string)=>{const values:Record<string,string>={dashboard:lang==='my'?'ပင်မစာမျက်နှာ':'Dashboard',pos:lang==='my'?'အရောင်း':'Point of Sale',inventory:lang==='my'?'ကုန်ပစ္စည်း':'Inventory',reports:lang==='my'?'အစီရင်ခံစာ':'Reports',settings:lang==='my'?'ဆက်တင်':'Settings',newSale:lang==='my'?'အရောင်းအသစ်':'New sale',search:lang==='my'?'ရှာဖွေပါ':'Search products, SKU or barcode...',checkout:lang==='my'?'ငွေရှင်းရန်':'Checkout',subtotal:lang==='my'?'စုစုပေါင်းခွဲ':'Subtotal',tax:lang==='my'?'အခွန်':'Tax (5%)',total:lang==='my'?'စုစုပေါင်း':'Total',complete:lang==='my'?'အရောင်းပြီးဆုံး':'Complete sale',lowStock:lang==='my'?'လက်ကျန်နည်း':'Low stock',todaySales:lang==='my'?'ယနေ့အရောင်း':'Today sales',transactions:lang==='my'?'ငွေရှင်းမှု':'Transactions',pending:lang==='my'?'စောင့်ဆိုင်း':'Pending sync'};return values[key]||key};

function App(){
 const [page,setPage]=useState('dashboard'); const [lang,setLang]=useState<'en'|'my'>('en'); const [dark,setDark]=useState(false); const [query,setQuery]=useState(''); const [cart,setCart]=useState<CartItem[]>([]); const [sales,setSales]=useState<Sale[]>(()=>JSON.parse(localStorage.getItem('cycleflow-sales')||JSON.stringify(initialSales))); const [offline,setOffline]=useState(()=>!navigator.onLine); const [toast,setToast]=useState(''); const [category,setCategory]=useState('All');
 useEffect(()=>{localStorage.setItem('cycleflow-sales',JSON.stringify(sales))},[sales]); useEffect(()=>{const on=()=>setOffline(false),off=()=>setOffline(true); addEventListener('online',on);addEventListener('offline',off);return()=>{removeEventListener('online',on);removeEventListener('offline',off)}},[]);
 const filtered=useMemo(()=>products.filter(p=>(category==='All'||p.category===category)&&[p.name,p.my,p.sku].some(v=>v.toLowerCase().includes(query.toLowerCase()))),[query,category]);
 const subtotal=cart.reduce((a,p)=>a+p.price*p.qty,0); const tax=Math.round(subtotal*.05); const total=subtotal+tax;
 const add=(p:Product)=>{setCart(c=>c.some(x=>x.id===p.id)?c.map(x=>x.id===p.id?{...x,qty:Math.min(x.qty+1,p.stock)}:x):[...c,{...p,qty:1}]); setToast(`${p.name} added`);setTimeout(()=>setToast(''),1800)};
 const complete=()=>{if(!cart.length)return; const sale:Sale={id:crypto.randomUUID(),receipt:`CF-${new Date().toISOString().slice(2,10).replaceAll('-','')}-${String(sales.length+1).padStart(3,'0')}`,total,items:cart.reduce((a,x)=>a+x.qty,0),status:offline?'PENDING_UPLOAD':'SYNCED',time:'Just now'};setSales([sale,...sales]);setCart([]);setToast(offline?'Saved offline — will sync automatically':'Sale completed successfully');setTimeout(()=>setToast(''),2500)};
 return <div className={dark?'app dark':'app'}><aside className="sidebar"><div className="brand"><div className="brandmark"><Bike size={23}/></div><div><b>CycleFlow</b><small>Retail OS</small></div></div><div className="store"><span className="live-dot"/>Main Store <ChevronRight size={15}/></div><nav>{[['dashboard',LayoutDashboard,t('dashboard',lang)],['pos',ShoppingCart,t('pos',lang)],['inventory',Boxes,t('inventory',lang)],['reports',BarChart3,t('reports',lang)]].map(([key,Icon,label])=><button key={String(key)} className={page===String(key)?'active':''} onClick={()=>setPage(String(key))}><Icon size={18}/><span>{label as string}</span>{key==='pos'&&cart.length>0&&<em>{cart.length}</em>}</button>)}</nav><div className="sidebar-bottom"><button onClick={()=>setPage('settings')}><Settings size={18}/>{t('settings',lang)}</button><div className="user"><div className="avatar">KO</div><div><b>Ko Aung</b><small>Owner</small></div><ChevronRight size={15}/></div></div></aside><main><header><div className="mobile-brand"><button className="iconbtn"><Menu size={21}/></button><b>CycleFlow</b></div><div className="crumb">Main Store <span>/</span> {page==='dashboard'?t('dashboard',lang):page==='pos'?t('pos',lang):page}</div><div className="header-actions"><button className="iconbtn" onClick={()=>setLang(lang==='en'?'my':'en')} title="Language"><Languages size={18}/><small>{lang.toUpperCase()}</small></button><button className="iconbtn" onClick={()=>setDark(!dark)}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button><div className={offline?'sync offline':'sync'}>{offline?<CloudOff size={16}/>:<Wifi size={16}/>}<span>{offline?'Offline':'Synced'}</span></div></div></header>{offline&&<div className="offline-banner"><CloudOff size={17}/><b>Offline mode</b><span>Sales are saved securely on this device and will sync when connection returns.</span><button onClick={()=>setOffline(false)}>Dismiss</button></div>}{page==='dashboard'&&<Dashboard sales={sales} setPage={setPage} lang={lang}/>} {page==='pos'&&<POS filtered={filtered} category={category} setCategory={setCategory} query={query} setQuery={setQuery} cart={cart} add={add} setCart={setCart} subtotal={subtotal} tax={tax} total={total} complete={complete} lang={lang}/>} {page==='inventory'&&<Inventory query={query} setQuery={setQuery} lang={lang}/>} {page==='reports'&&<Reports sales={sales}/>} {page==='settings'&&<SettingsPage lang={lang}/>} </main>{toast&&<div className="toast"><Check size={17}/>{toast}</div>}</div>
}
function PageTitle({eyebrow,title,sub,action}:{eyebrow:string;title:string;sub:string;action?:ReactNode}){return <div className="page-title"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{sub}</p></div>{action}</div>}
function Dashboard({sales,setPage,lang}:{sales:Sale[];setPage:(p:string)=>void;lang:string}){const today=sales.filter(s=>s.time!=='Yesterday');return <section className="content"><PageTitle eyebrow="TUESDAY, 15 SEPTEMBER 2026" title={lang==='my'?'မင်္ဂလာပါ၊ ကိုအောင်':'Good morning, Ko Aung'} sub="Here’s what’s happening in your store today." action={<button className="primary" onClick={()=>setPage('pos')}><Plus size={17}/>{t('newSale',lang)}</button>}/><div className="stats"><Stat icon={CircleDollarSign} label={t('todaySales',lang)} value={money(today.reduce((a,s)=>a+s.total,0))} trend="+12.8%"/><Stat icon={ShoppingCart} label={t('transactions',lang)} value="24" trend="+8.2%"/><Stat icon={TrendingUp} label="Gross profit" value="1.24M MMK" trend="+14.6%"/><Stat icon={CloudOff} label={t('pending',lang)} value={String(sales.filter(s=>s.status!=='SYNCED').length)} trend="Needs attention" warn/></div><div className="grid-two"><div className="panel chart-panel"><div className="panel-head"><div><b>Sales overview</b><small>Last 7 days</small></div><select><option>This week</option><option>This month</option></select></div><div className="chart"><div className="ylabels"><span>1.5M</span><span>1.0M</span><span>500K</span><span>0</span></div><div className="bars">{[.52,.72,.46,.86,.64,.92,.7].map((v,i)=><div className="bar-col" key={i}><div className="bar" style={{height:`${v*100}%`}}/><small>{['Wed','Thu','Fri','Sat','Sun','Mon','Tue'][i]}</small></div>)}</div></div></div><div className="panel"><div className="panel-head"><div><b>Quick actions</b><small>Common workflows</small></div></div><div className="quick-grid"><button onClick={()=>setPage('pos')}><ShoppingCart size={19}/><span>New sale</span><ChevronRight size={15}/></button><button onClick={()=>setPage('inventory')}><PackagePlus size={19}/><span>Receive stock</span><ChevronRight size={15}/></button><button onClick={()=>setPage('inventory')}><Tag size={19}/><span>Add product</span><ChevronRight size={15}/></button><button onClick={()=>setPage('reports')}><FileText size={19}/><span>View reports</span><ChevronRight size={15}/></button></div></div></div><div className="panel recent"><div className="panel-head"><div><b>Recent transactions</b><small>Latest activity across your store</small></div><button className="textbtn" onClick={()=>setPage('reports')}>View all <ChevronRight size={15}/></button></div><SalesTable sales={sales.slice(0,4)}/></div></section>}
function Stat({icon:Icon,label,value,trend,warn}:{icon:any;label:string;value:string;trend:string;warn?:boolean}){return <div className="stat"><div className="stat-icon"><Icon size={19}/></div><small>{label}</small><strong>{value}</strong><span className={warn?'warn':''}>{trend}</span></div>}
function POS({filtered,category,setCategory,query,setQuery,cart,add,setCart,subtotal,tax,total,complete,lang}:{filtered:Product[];category:string;setCategory:(x:string)=>void;query:string;setQuery:(x:string)=>void;cart:CartItem[];add:(p:Product)=>void;setCart:any;subtotal:number;tax:number;total:number;complete:()=>void;lang:string}){return <section className="content"><PageTitle eyebrow="SALES / CHECKOUT" title={t('pos',lang)} sub="Search, scan, and sell in seconds." action={<div className="device-chip"><span className="live-dot"/> Register 01 <small>Online</small></div>}/><div className="pos-layout"><div className="products-area"><div className="searchrow"><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('search',lang)}/>{query&&<X size={16} onClick={()=>setQuery('')}/>}</div><button className="scanbtn"><span>▦</span> Scan barcode</button></div><div className="chips">{['All','Bicycles','Helmets','Lights','Locks','Tires','Tools','Accessories'].map(c=><button className={category===c?'selected':''} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div><div className="product-grid">{filtered.map(p=><button className="product" key={p.id} onClick={()=>add(p)}><div className="product-art" style={{background:p.color}}><Bike size={42}/><span className={p.stock<=p.min?'stock low':'stock'}>{p.stock} left</span></div><div className="product-info"><b>{lang==='my'?p.my:p.name}</b><small>{p.sku} · {p.category}</small><strong>{money(p.price)}</strong></div><div className="add"><Plus size={16}/></div></button>)}</div></div><aside className="cart"><div className="cart-head"><div><b>Current sale</b><small>{cart.length?`${cart.reduce((a,x)=>a+x.qty,0)} items`:'No items yet'}</small></div><button className="iconbtn" onClick={()=>setCart([])} disabled={!cart.length}><Trash2 size={17}/></button></div>{!cart.length?<div className="empty-cart"><ShoppingCart size={34}/><b>Your cart is empty</b><span>Choose a product to start a new sale.</span></div>:<><div className="cart-items">{cart.map(i=><div className="cart-item" key={i.id}><div className="mini-art" style={{background:i.color}}><Bike size={18}/></div><div><b>{i.name}</b><small>{money(i.price)}</small></div><div className="qty"><button onClick={()=>setCart((c:CartItem[])=>i.qty===1?c.filter(x=>x.id!==i.id):c.map(x=>x.id===i.id?{...x,qty:x.qty-1}:x))}>−</button><span>{i.qty}</span><button onClick={()=>add(i)}>+</button></div></div>)}</div><div className="bill"><div><span>{t('subtotal',lang)}</span><b>{money(subtotal)}</b></div><div><span>{t('tax',lang)}</span><b>{money(tax)}</b></div><div className="grand"><span>{t('total',lang)}</span><strong>{money(total)}</strong></div><button className="primary checkout" onClick={complete}><Check size={18}/>{t('complete',lang)}<span>Ctrl + Enter</span></button><button className="hold">Hold sale</button></div></>}</aside></div></section>}
function SalesTable({sales}:{sales:Sale[]}){return <div className="table-wrap"><table><thead><tr><th>Receipt</th><th>Items</th><th>Amount</th><th>Time</th><th>Status</th></tr></thead><tbody>{sales.map(s=><tr key={s.id}><td><b>{s.receipt}</b></td><td>{s.items} items</td><td><b>{money(s.total)}</b></td><td>{s.time}</td><td><span className={`status ${s.status.toLowerCase()}`}>{s.status==='SYNCED'?'Synced':s.status==='CONFLICT'?'Conflict':'Pending sync'}</span></td></tr>)}</tbody></table></div>}
function Inventory({query,setQuery,lang}:{query:string;setQuery:(x:string)=>void;lang:string}){const list=products.filter(p=>[p.name,p.my,p.sku].some(v=>v.toLowerCase().includes(query.toLowerCase())));return <section className="content"><PageTitle eyebrow="CATALOG / STOCK" title={t('inventory',lang)} sub="Manage products, stock levels, and bicycle serial numbers." action={<button className="primary"><Plus size={17}/> Add product</button>}/><div className="inventory-kpis"><Stat icon={Boxes} label="Total products" value="248" trend="+6 this month"/><Stat icon={PackagePlus} label="Units on hand" value="1,284" trend="Healthy"/><Stat icon={CloudOff} label={t('lowStock',lang)} value="8" trend="Review now" warn/></div><div className="panel inventory-panel"><div className="panel-head"><div><b>Product catalog</b><small>All active products</small></div><div className="search compact"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search catalog..."/></div></div><div className="table-wrap"><table><thead><tr><th>Product</th><th>SKU</th><th>Category</th><th>Price</th><th>Stock</th><th>Serial / frame</th></tr></thead><tbody>{list.map(p=><tr key={p.id}><td><div className="table-product"><div className="mini-art" style={{background:p.color}}><Bike size={18}/></div><div><b>{p.name}</b><small>{p.my}</small></div></div></td><td>{p.sku}</td><td>{p.category}</td><td><b>{money(p.price)}</b></td><td><span className={p.stock<=p.min?'stock-number low':'stock-number'}>{p.stock} units</span></td><td>{p.serial||'—'}</td></tr>)}</tbody></table></div></div></section>}
function Reports({sales}:{sales:Sale[]}){return <section className="content"><PageTitle eyebrow="INSIGHTS / EXPORTS" title="Reports" sub="Understand your sales and inventory performance." action={<button className="primary"><FileText size={17}/> Export CSV</button>}/><div className="report-cards"><div className="panel report-big"><small>Sales this month</small><strong>18.64M MMK</strong><span className="positive">↑ 18.4% vs last month</span><div className="spark">{[30,55,40,75,52,80,65,90,72,100].map((h,i)=><i style={{height:`${h}%`}} key={i}/>)}</div></div><div className="panel report-big"><small>Top category</small><strong>Bicycles</strong><span>42% of total revenue</span><div className="progress"><i style={{width:'42%'}}/></div><div className="report-row"><span>Accessories</span><b>28%</b></div><div className="report-row"><span>Safety gear</span><b>18%</b></div></div></div><div className="panel recent"><div className="panel-head"><div><b>Offline & synchronization log</b><small>All local transactions are retained until acknowledged by the server.</small></div><button className="textbtn"><RefreshCw size={15}/> Retry pending</button></div><SalesTable sales={sales}/></div></section>}
function SettingsPage({lang}:{lang:string}){return <section className="content"><PageTitle eyebrow="SYSTEM / PREFERENCES" title={t('settings',lang)} sub="Configure your store, register, and staff access."/><div className="settings-grid"><div className="panel settings-card"><div className="settings-icon"><Users size={20}/></div><b>Store & staff</b><p>Manage registers, users, roles, and device approval.</p><button className="textbtn">Open settings <ChevronRight size={15}/></button></div><div className="panel settings-card"><div className="settings-icon"><RefreshCw size={20}/></div><b>Offline synchronization</b><p>Device ID: REGISTER-01<br/>Last sync: Just now<br/>Queue: 0 transactions</p><span className="status synced">Healthy</span></div><div className="panel settings-card"><div className="settings-icon"><Printer size={20}/></div><b>Receipt & printer</b><p>Configure receipt header, footer, and thermal printer connection.</p><button className="textbtn">Configure <ChevronRight size={15}/></button></div><div className="panel settings-card"><div className="settings-icon"><Languages size={20}/></div><b>Language & currency</b><p>English / မြန်မာ<br/>Myanmar Kyat (MMK)</p><span className="status synced">Active</span></div></div></section>}
export default App;
